### ISSUE TITLE
Driver's Station does not reliably push control frames.

### ISSUE THREAD

**Issue by 3wheelok** [gizmo-platform/gizmo#13] opened 2024-05-30 22:19 UTC
First, I want to say thank you to all involved with this project! It is truly an awesome accomplishment.

I was using the following software:
driver-station.img downloaded on 30 May 2024 (no version number found)
gizmo.exe version 0.0.12
gss_v0.0.2.uf2 

After successfully pairing the driver station to the gizmo (green network led, and blinking white field led)..........

If the Logitech Controller is _**already**_ plugged into the driver's station **_before_** applying power to the driver's station, the Logitech Controller data is not sent to the user pico. All joystick data is 127 and all button data is 0 no matter what controls on the joystick are actuated.

If you apply power to the driver's station with the Logitech Controller unplugged. And you plug the Logitech Controller into the drivers station after sync process (Green and white blinking LEDs) has completed, data is received at the user pico, and it functions as expected with one exception.

The GIZMO_AXIS_LX, GIZMO_AXIS_LY, GIZMO_AXIS_RX and GIZMO_AXIS_RY data is 0 where I would have expected 127.

If any button is actuated or any joystick is moved on the Logitech Controller, the values of GIZMO_AXIS_LX, GIZMO_AXIS_LY, GIZMO_AXIS_RX and GIZMO_AXIS_RY become 127, or the appropriate joystick value.

**Comment by gdyoung93** [comment] 2024-06-09 18:02
"If the Logitech Controller is plugged into the driver's station when applying power to the driver's station" - this implies plugging in the controller while the Driver Station is booting.  The Joystick and Driver Station, once connected should really never need to be disconnected. I suggest assuming no "hot insertion".  Try plugging the joystick in before applying power to the Driver Station.

**Comment by 3wheelok** [comment] 2024-06-09 20:04
Sorry for the confusion. I did not mean to imply any hot swapping in that paragraph, nor was plugging in the joystick during boot. I intended the following:
"If the Logitech Controller is **_already_** plugged in to the driver's station when power is applied to the drivers station..."

**Comment by the-maldridge** [comment] 2024-09-01 19:09
There are 2 distinct problems here.  One has been identified and resolved.  The issue with the axis data all reading out as 0 instead of the centered 127 value has to do with the way the kernel level joystick driver is implemented.  The joystick is actually being read, but because the driver is event based, until you actually *do* something with the joystick or buttons there are no events, and the uninitialized values are all at the minimums.  I've drafted a patch that watches for this scenario and looks for the value of the 0th axis to change from the kernel initialized default of -32767 (these get clamped to a uint8 to make things on the embedded side easier).

I am still troubleshooting the issue where data just never gets read, but I believe I have made progress on that having just identified a sequence of error handlers that can result in the driver's station daemon no longer polling the gamepad.  I will add a watchdog to restart the driver's station process if the loop is no longer running.

**Comment by the-maldridge** [comment] 2024-09-02 05:45
I am not able to reproduce the case where control data just never picks up, but I've received enough reports of this specific failure mode that I do not believe that its a fluke.  To bulk resolve this and similar issues, the driver's station now includes watchdogs that will force a process restart if things don't look right.

**Comment by the-maldridge** [comment] 2024-09-13 02:07
At this point I'm reasonably convinced we've addressed this issue between additional timeouts, fixes to the gamepad behaviors around boot, and improved indication at the Gizmo end for when things are and are not connected.  Are there further issues you believe need to be addressed that are not in release build v0.1.2 prior to closing this issue @3wheelok ?

**Comment by the-maldridge** [comment] 2024-10-30 06:58
I'm closing this as obsolete.  There are now watchdogs throughout the entire system, the driver's station architecture has changed since this was opened, and the Gizmo now dynamically re-aquires the control stream in the event of a dropout.  For further control systems issues, please open a new issue to keep the problem space focused.

**Closed by the-maldridge** 2024-10-30 06:58 UTC
